// src/components/Plum.jsx
import React, { useState, useEffect, useRef } from "react";

const MIN_BRANCH = 30;
const r180 = Math.PI;
const r90 = Math.PI / 2;
const r15 = Math.PI / 12;
const color = "#88888825";

const polar2cart = (x = 0, y = 0, r = 0, theta = 0) => {
  const dx = r * Math.cos(theta);
  const dy = r * Math.sin(theta);
  return [x + dx, y + dy];
};

const RandomBranches = () => {
  const canvasRef = useRef(null);
  const [size, setSize] = useState({ width: 400, height: 400 });
  const [stopped, setStopped] = useState(false);
  const [ctx, setCtx] = useState(null);
  const [steps, setSteps] = useState([]);
  const [prevSteps, setPrevSteps] = useState([]);

  useEffect(() => {
    const canvas = canvasRef.current;
    const context = canvas.getContext("2d");

    const dpr = window.devicePixelRatio || 1;
    const bsr =
      context.webkitBackingStorePixelRatio ||
      context.mozBackingStorePixelRatio ||
      context.msBackingStorePixelRatio ||
      context.oBackingStorePixelRatio ||
      context.backingStorePixelRatio ||
      1;

    const dpi = dpr / bsr;

    canvas.style.width = `${size.width}px`;
    canvas.style.height = `${size.height}px`;
    canvas.width = dpi * size.width;
    canvas.height = dpi * size.height;

    setCtx(context);

    const random = Math.random;
    const { width, height } = canvas;

    const step = (x, y, rad, counter = 0) => {
      const length = random() * 6;
      counter++;

      const [nx, ny] = polar2cart(x, y, length, rad);

      context.beginPath();
      context.moveTo(x, y);
      context.lineTo(nx, ny);
      context.stroke();

      const rad1 = rad + random() * r15;
      const rad2 = rad - random() * r15;

      if (
        nx < -100 ||
        nx > size.width + 100 ||
        ny < -100 ||
        ny > size.height + 100
      )
        return;

      const rate = counter <= MIN_BRANCH ? 0.8 : 0.5;

      if (random() < rate) steps.push(() => step(nx, ny, rad1, counter));

      if (random() < rate) steps.push(() => step(nx, ny, rad2, counter));
    };

    const randomMiddle = () => random() * 0.6 + 0.2;

    const animate = () => {
      if (stopped) return;

      setPrevSteps([...steps]);
      setSteps([]);

      if (prevSteps.length === 0) {
        setStopped(true);
        return;
      }

      prevSteps.forEach((i) => {
        if (random() < 0.5) steps.push(i);
        else i();
      });

      requestAnimationFrame(animate);
    };

    setSteps([
      () => step(randomMiddle() * size.width, -5, r90),
      () => step(randomMiddle() * size.width, size.height + 5, -r90),
      () => step(-5, randomMiddle() * size.height, 0),
      () => step(size.width + 5, randomMiddle() * size.height, r180),
    ]);

    animate();

    return () => setStopped(true);
  }, [size, steps, prevSteps, stopped]);

  useEffect(() => {
    if (!ctx) return;
    ctx.clearRect(0, 0, size.width, size.height);
    ctx.lineWidth = 1;
    ctx.strokeStyle = color;
  }, [ctx, size]);

  const handleResize = () => {
    setSize({
      width: window.innerWidth,
      height: window.innerHeight,
    });
  };

  useEffect(() => {
    window.addEventListener("resize", handleResize);
    return () => window.removeEventListener("resize", handleResize);
  }, []);

  const handleStart = () => setStopped(false);

  const mask = "radial-gradient(circle, transparent, black)";

  return (
    <div
      className="fixed top-0 bottom-0 left-0 right-0 pointer-events-none print:hidden"
      style={{
        zIndex: -99,
        position: "fixed",
        top: 0,
        left: 0,
        bottom: 0,
        right: 0,
        maskImage: mask,
        WebkitMaskImage: mask,
      }}
    >
      <canvas
        ref={canvasRef}
        width={size.width}
        height={size.height}
        onClick={handleStart}
      />
    </div>
  );
};

export default RandomBranches;

// src/components/Plum.vue
<script setup>
import { ref, reactive, onMounted, computed } from "vue";
import { useWindowSize, useRafFn } from "@vueuse/core";

const r180 = Math.PI;
const r90 = Math.PI / 2;
const r15 = Math.PI / 12;
const color = "#88888825";

const el = ref(null);

const { random } = Math;
const size = reactive(useWindowSize());

const start = ref(() => {});
const MIN_BRANCH = 30;
const len = ref(6);
const stopped = ref(false);

function initCanvas(canvas, width = 400, height = 400, _dpi) {
  const ctx = canvas.getContext("2d");

  const dpr = window.devicePixelRatio || 1;
  const bsr =
    ctx.webkitBackingStorePixelRatio ||
    ctx.mozBackingStorePixelRatio ||
    ctx.msBackingStorePixelRatio ||
    ctx.oBackingStorePixelRatio ||
    ctx.backingStorePixelRatio ||
    1;

  const dpi = _dpi || dpr / bsr;

  canvas.style.width = `${width}px`;
  canvas.style.height = `${height}px`;
  canvas.width = dpi * width;
  canvas.height = dpi * height;
  ctx.scale(dpi, dpi);

  return { ctx, dpi };
}

function polar2cart(x = 0, y = 0, r = 0, theta = 0) {
  const dx = r * Math.cos(theta);
  const dy = r * Math.sin(theta);
  return [x + dx, y + dy];
}

onMounted(async () => {
  const canvas = el.value;
  const { ctx } = initCanvas(canvas, size.width, size.height);
  const { width, height } = canvas;

  let steps = [];
  let prevSteps = [];

  const step = (x, y, rad, counter = { value: 0 }) => {
    const length = random() * len.value;
    counter.value += 1;

    const [nx, ny] = polar2cart(x, y, length, rad);

    ctx.beginPath();
    ctx.moveTo(x, y);
    ctx.lineTo(nx, ny);
    ctx.stroke();

    const rad1 = rad + random() * r15;
    const rad2 = rad - random() * r15;

    if (
      nx < -100 ||
      nx > size.width + 100 ||
      ny < -100 ||
      ny > size.height + 100
    )
      return;

    const rate = counter.value <= MIN_BRANCH ? 0.8 : 0.5;

    if (random() < rate) steps.push(() => step(nx, ny, rad1, counter));

    if (random() < rate) steps.push(() => step(nx, ny, rad2, counter));
  };

  let lastTime = performance.now();
  const interval = 1000 / 40;

  let controls;

  const frame = () => {
    if (performance.now() - lastTime < interval) return;

    prevSteps = steps;
    steps = [];
    lastTime = performance.now();

    if (!prevSteps.length) {
      controls.pause();
      stopped.value = true;
    }

    prevSteps.forEach((i) => {
      if (random() < 0.5) steps.push(i);
      else i();
    });
  };

  controls = useRafFn(frame, { immediate: false });

  const randomMiddle = () => random() * 0.6 + 0.2;

  start.value = () => {
    controls.pause();
    ctx.clearRect(0, 0, width, height);
    ctx.lineWidth = 1;
    ctx.strokeStyle = color;
    prevSteps = [];
    steps = [
      () => step(randomMiddle() * size.width, -5, r90),
      () => step(randomMiddle() * size.width, size.height + 5, -r90),
      () => step(-5, randomMiddle() * size.height, 0),
      () => step(size.width + 5, randomMiddle() * size.height, r180),
    ];
    if (size.width < 500) steps = steps.slice(0, 2);
    controls.resume();
    stopped.value = false;
  };

  start.value();
});
const mask = computed(() => "radial-gradient(circle, transparent, black);");
</script>

<template>
  <div
    class="fixed top-0 bottom-0 left-0 right-0 pointer-events-none print:hidden"
    style="z-index: -99; position: fixed;top: 0;left: 0;bottom: 0;right: 0;"
    :style="`mask-image: ${mask};--webkit-mask-image: ${mask};`"
  >
    <canvas ref="el" width="400" height="400" />
    <h1>你好</h1>
  </div>
</template>
